### ISSUE TITLE
Not finding filesystem on pi 4 with kali

### ISSUE THREAD

**Issue by djesys** [hcfman/overlayroot#1]
Hi,
I wonder why the script is not detecting my rootfs.

./overlayRoot.sh 
check if we can locate the root device based on fstab
no success, try if a filesystem with label 'rootfs' is avaialble
no luck either, try to further parse fstab's root device definition
try if fstab contains a PARTUUID definition
-e could not find a root filesystem device in fstab. Make sure that fstab contains a device definition or a PARTUUID entry for / or that the root filesystem has a label 'rootfs' assigned to it

lsblk -f
NAME        FSTYPE      FSVER LABEL  UUID                                 FSAVAIL FSUSE% MOUNTPOINTS
mmcblk0                                                                                  
├─mmcblk0p1 vfat        FAT32 BOOT   8945-EB60                             163.7M    35% /boot
├─mmcblk0p2 ext4        1.0   ROOTFS c69893c8-3f3d-4d34-aab7-6509758ee5a3   32.9G    25% /
└─mmcblk0p3 crypto_LUKS 2            071e06ed-eba8-4e15-b7ee-29248b407847               

cat /etc/fstab
`# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc           proc    defaults          0       0

UUID=c69893c8-3f3d-4d34-aab7-6509758ee5a3 /               ext4 errors=remount-ro 0       1
LABEL=BOOT      /boot           vfat    defaults          0       2
`

**Comment by hcfman** [comment]
I've never tried this on Kali. That project was meant to be just a github wrapper around someone else's work.

However, last weekend with the standard raspyberrypi OS it also didn't work for me. I have another raspberrypi where it does work, so I simply used that one. Likely I solved the problem before.

When I get some time, which could be the weekend but maybe earlier, I'll copy the working one I have with this one and likely just update this one with the working one because it's stopped working with the standard raspberrypi OS anyway. Possibly it will also fix it for kali.

Kim

**Comment by djesys** [comment]
thanks for getting back!
there are a few versions out there, however, none work. yours seemed the most recent, that's why i wrote you.
Please see what you can do. i cannot effectively run my pi without an overlay. it looks like nothing big, it's just not recognizing the rootfs.

best!

12 Oct 2022 08:39:35 Kim Hendrikse ***@***.***>:

**Comment by hcfman** [comment]
As mentioned. I don't do anything with kali. But I checked the diffs between my working version I installed on raspberrypi OS in the weekend and the one committed here. I don't see anything problematic with it so I replaced the one I had here for a long while with the one I know works on a recent version of pi.

Hope that also works with kali. Let me know.

Kim Hendrikse

**Comment by hcfman** [comment]
Just on a side note I've done a lot of playing around with the overlayFS approach. So if this doesn't work as well, I may possibly be challenged into looking directly into the kali issue. I also use it with a twist on the jetson projects. And for some of my pi SD card only projects I do have an "unpublished" code with uses a memory overlay to resize an installed OS to a smaller size so that I can use my StalkedByTheState approach, which normally uses an SSD, but with SD card only. i.e. I have a read-only mounted OS but have a read/write partition for data and also a read-only but remountable partition for configuration.

In essentially, I'm also installing my StalkedByTheState project onto raspberrypi's but not with the intention of doing computer vision but with the intention of using the state machine/automation engine part of it.

If you are interested, the StalkedByTheState project has variations of this theme:

https://github.com/hcfman/sbts-install

Kim Hendrikse

**Comment by hcfman** [comment]
In case I didn’t say it clearly. I committed a change. Please see if that works now with the new overlay script

**Comment by djesys** [comment]
Just tried it out, but the error message is the same unfortunately. Why do you think it is not recognizing the ROOTFS label or UUID ?

**Comment by hcfman** [comment]
That’s hard to say without testing. However I suspect the error message is misleading.

I’ll get a pi and install Kali in the weekend and try and replicate your situation. Please let me know the contents of the cmdline.txt file so I can be sure I’m solving the same problem.

**Comment by djesys** [comment]
Hi, thanks so much for doing this ! My cmdline.txt:

`console=serial0,115200 console=tty1 root=PARTUUID=da77a68a-02 rootfstype=ext4 fsck.repair=yes rootwait net.ifnames=0 init=/sbin/overlayRoot.sh`

**Comment by hcfman** [comment]
Try it now. It should now convert rootDev specifications in the form UUID= or PARTUID= to device paths first and then succeed fine I think.

**Comment by djesys** [comment]
Hi, just did. Same error message during boot. Can I do anything to debug it ?

**Comment by hcfman** [comment]
Please contact me directly.- CheersKimOn 16 Oct 2022, at 12:41, lostsock ***@***.***> wrote:﻿
Hi, just did. Same error message during boot. Can I do anything to debug it ?

**Comment by hcfman** [comment]
But yeah. You could put echo statements in the script to find out which part is failing.You should be able to contact me from my profile. Take direct contact and we’ll take it from there. - CheersKimOn 16 Oct 2022, at 12:41, lostsock ***@***.***> wrote:﻿
Hi, just did. Same error message during boot. Can I do anything to debug it ?

**Comment by hcfman** [comment]
Print the value in rootDev before it does the blkid on it. Or simply replace the reference in /etc/fstab that starts with UUID= with the path to the root partition. I.e. /dev/mmcblk0p2I’d like to help you solve it properly but then you have to contact me directly.- CheersKimOn 16 Oct 2022, at 12:41, lostsock ***@***.***> wrote:﻿
Hi, just did. Same error message during boot. Can I do anything to debug it ?

**Comment by hcfman** [comment]
If the variable rootDev contains /dev/mmcblk0p2 at the time of the first test with blkid then it should work. I tested the code snippets on the fstab input that you gave me and it correctly resolved to /dev/mmcblk0p2 so it should work. debug that, but I don't actually want to download and install kali linux to test this sorry.

And if you have further questions or please also post the output of the command together with the values of the variables, particularly rootDev.

**Comment by djesys** [comment]
Hi Kim! I am not able to message you directly through github. please reply to djesys@riseup.net
I will be trying out you suggestions. thank you for your time!

**Comment by hcfman** [comment]
Apparently changing UUID=* to a full pathname to the 2nd partition, i.e. /dev/mmcblk0p2 fix it.

For the record, I didn't download kali to try this. I have no need for a penetration testing tool so when I learned that this is what kali is I didn't download it. Just in case someone tries to frame me for something I didn't do.

Kim

**Comment by hcfman** [comment]
Oh, I wasn't implying djesys, far from it, just covering myself for anything in the future. As this sort of tool make's me uncomfortable, so I want my statement on public record.
